# Generated by Django 4.0.2 on 2022-04-14 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='owned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='picturemodel',
            name='rest_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_owner', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menu',
            name='owned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_owned', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='likerestaurant',
            name='like_restaurant_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_restaurant_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likerestaurant',
            name='like_restaurant_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_restaurant_to', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='likepost',
            name='like_post_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_post_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likepost',
            name='like_post_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_post_to', to='restaurant.post'),
        ),
        migrations.AddField(
            model_name='follow',
            name='follow_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='follow_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_to', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comments_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='comments_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_to', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='reply_to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply_to', to='restaurant.comments'),
        ),
    ]
