# Generated by Django 4.0.2 on 2022-04-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, default='static/images/default_logo.png', null=True, upload_to='static/images/'),
        ),
    ]
