# Generated by Django 4.0.2 on 2022-04-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_restaurant_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturemodel',
            name='restaurant_picture',
            field=models.ImageField(blank=True, default='static/images/qq.png', null=True, upload_to='static/images/'),
        ),
    ]
