# Generated by Django 4.0.2 on 2022-04-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restifyuser',
            name='avatar',
            field=models.ImageField(blank=True, default='static/images/default_avatar.png', null=True, upload_to='static/images/'),
        ),
    ]
